# Data preparation for building Uni-Mol-MeCAPs

## Download and unzip

This procedure is following [this reference](https://github.com/jensengroup/ESNUEL_ML).

In [1]:
# Download and check included files
!wget -O data.tar.xz https://sid.erda.dk/share_redirect/c7LF5NaYvH; tar -tvf data.tar.xz | head

--2025-09-26 14:20:16--  https://sid.erda.dk/share_redirect/c7LF5NaYvH
Resolving sid.erda.dk (sid.erda.dk)... 130.225.104.13
Connecting to sid.erda.dk (sid.erda.dk)|130.225.104.13|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1170060920 (1.1G)
Saving to: ‘data.tar.xz’

data.tar.xz         100%[===================>]   1.09G  1.79MB/s    in 7m 37s

2025-09-26 14:27:55 (2.44 MB/s) - ‘data.tar.xz’ saved [1170060920/1170060920]

drwxr-xr-x nicolairee/staff  0 2024-08-15 19:36 data/
drwxr-xr-x nicolairee/staff  0 2024-10-03 02:57 data/benchmark/
-rw-r--r-- nicolairee/staff 120 2024-08-15 22:53 data/._.DS_Store
tar: Ignoring unknown extended header keyword 'SCHILY.fflags'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.FinderInfo'
-rw-r--r-- nicolairee/staff 6148 2024-08-15 22:53 data/.DS_Store
drwxr-xr-x nicolairee/staff    0 2024-08-16 21:57 data/uncertaintyEstimates/
drwxr-xr-x nicolairee/staff    0 2024-08-15 20:58 data/QMdata4ML/
drwxr-xr-x nicolairee/staff    0 2024-08-30 21:56 data/hydrolysis/
-rw-r--r-- nicolairee/staff 3491 2024-08-30 21:06 data/hydrolysis/101016jjtice202106045_data.csv
-rw-r--r-- nicolairee/staff 48529 2024-08-30 21:56 data/hydrolysis/CAEHydrolysisDataset.csv
-rw-r--r-- nicolairee/staff 11270 2024-08-30 21:07 data/hydrolysis/public_hydrolysis_data_tebes_stevens.csv
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemTextContentLanguage'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemKeyphraseVersion'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemKeyphraseLabels'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemKeyphraseConfidences'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemTextContentLanguage'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemKeyphraseVersion'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemKeyphraseLabels'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemKeyphraseConfidences'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.macl'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.lastuseddate#PS'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.macl'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.lastuseddate#PS'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.macl'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.lastuseddate#PS'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.macl'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.lastuseddate#PS'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemTextContentLanguage'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemKeyphraseVersion'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.macl'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.lastuseddate#PS'
tar: stdout: write error

In [2]:
# Now unzip necessary data 'QMdata4ML' to current directory
!tar --extract \
    --file=data.tar.xz \
    --xz \
    --strip-components=1 \
    --directory=. \
    data/QMdata4ML

tar: Ignoring unknown extended header keyword 'SCHILY.fflags'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.FinderInfo'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemTextContentLanguage'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemKeyphraseVersion'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemKeyphraseLabels'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemKeyphraseConfidences'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemTextContentLanguage'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemKeyphraseVersion'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemKeyphraseLabels'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemKeyphraseConfidences'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.macl'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.lastuseddate#PS'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.macl'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.lastuseddate#PS'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.macl'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.lastuseddate#PS'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.macl'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.lastuseddate#PS'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemTextContentLanguage'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemKeyphraseVersion'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.macl'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.lastuseddate#PS'

## Reference split (from the paper written by [Ree et. al.](https://doi.org/10.1039/D4SC07297A))

Since our procedure requires dataset to make the column containing 'train', 'val' and 'test', the integrated split column will be divided to each fold by the following procedure.

In [1]:
# Trial
import pandas as pd
pd.read_csv('./QMdata4ML/df_elec_x.csv.gz',index_col=0,nrows=5)

,smiles,elec_sites,elec_names,MAA_values,elec_GCS_3_cm5,Set,elec_SMI2GCS_3_cm5,elec_SMI2GCS_5_cm5,elec_RDKitCountFP_512,elec_RDKitGasteigerGCS_5,elec_AtomNumGCS_5
0,NOCc1cccc(I)c1,3,double_bond,90.348433,"[-0.01706, 0.12057, -0.11146, -0.08969, 0.0, -...",Train_fold5,"[-0.00668, 0.12661, -0.09866, -0.09247, 0.0, -...","[-0.00668, 0.12661, -0.09866, -0.09247, 0.0, -...","[4, 0, 4, 5, 2, 3, 0, 4, 3, 6, 0, 6, 4, 1, 0, ...","[-0.01928812973227673, 0.0929936027236162, -0....","[6, 6, 6, 6, 0.0, 8, 1, 1, 6, 1, 0.0, 6, 1, 0...."
1,NOCc1cccc(I)c1,4,double_bond,94.924314,"[-0.08969, -0.01706, -0.08484, 0.09939, 0.0, 0...",Train_fold2,"[-0.09247, -0.00668, -0.07901, 0.0887, 0.0, 0....","[-0.09247, -0.00668, -0.07901, 0.0887, 0.0, 0....","[4, 0, 4, 7, 0, 1, 0, 4, 1, 6, 0, 4, 4, 1, 0, ...","[-0.056572952259338685, -0.01928812973227673, ...","[6, 6, 6, 1, 0.0, 6, 6, 0.0, 6, 1, 0.0, 0.0, 0..."
2,NOCc1cccc(I)c1,5,double_bond,91.330269,"[-0.08484, -0.10499, -0.08969, 0.09122, 0.0, 0...",Train_fold3,"[-0.07901, -0.09933, -0.09247, 0.08588, 0.0, 0...","[-0.07901, -0.09933, -0.09247, 0.08588, 0.0, 0...","[2, 0, 4, 7, 0, 3, 0, 4, 2, 3, 0, 5, 2, 0, 0, ...","[-0.060854479918004876, -0.04882194239545837, ...","[6, 6, 6, 1, 0.0, 6, 1, 0.0, 6, 1, 0.0, 0.0, 0..."
3,NOCc1cccc(I)c1,6,double_bond,102.683928,"[-0.10499, 0.01492, -0.08484, 0.08707, 0.0, 0....",Train_fold1,"[-0.09933, 0.00749, -0.07901, 0.08466, 0.0, 0....","[-0.09933, 0.00749, -0.07901, 0.08466, 0.0, 0....","[0, 0, 5, 6, 0, 3, 0, 4, 2, 1, 0, 7, 3, 0, 0, ...","[-0.04882194239545837, 0.013342809000888595, -...","[6, 6, 6, 1, 0.0, 53, 6, 0.0, 6, 1, 0.0, 0.0, ..."
4,NOCc1cccc(I)c1,7,double_bond,276.204538,"[0.01492, 0.00479, -0.11146, -0.10499, 0.0, 0....",Train_fold3,"[0.00749, 0.01751, -0.09866, -0.09933, 0.0, 0....","[0.00749, 0.01751, -0.09866, -0.09933, 0.0, 0....","[2, 0, 5, 6, 2, 3, 0, 4, 3, 2, 0, 6, 3, 0, 0, ...","[0.013342809000888595, -0.04430373540190993, -...","[6, 53, 6, 6, 0.0, 0.0, 0.0, 0.0, 6, 1, 0.0, 6..."

In [ ]:
# Make name col from original data
df_origin = pd.read_csv('./QMdata4ML/df_ChEMBL50K.csv.gz',index_col=0)

df_elec = pd.read_csv('./QMdata4ML/df_elec_x.csv.gz',index_col=0)
df_nuc  = pd.read_csv('./QMdata4ML/df_nuc_x.csv.gz',index_col=0)

smi_dict = {row['smiles']: row['name'] for idx, row in df_origin.iterrows()}

df_elec['name'] = df_elec['smiles'].map(smi_dict)
df_nuc['name'] = df_nuc['smiles'].map(smi_dict)

# Create indivisual 'Fold' columns
def convert_fold(name, fold_num=1):
    if 'train' in name.lower():
        if name.lower() == f'train_fold{fold_num}':
            return 'val'
        else:
            return 'train'
    else:
        return name.lower()

for fnum in range(1,6):
    df_elec[f'Set_fold{fnum}'] = df_elec['Set'].apply(lambda f: convert_fold(f,fnum))
    df_nuc[f'Set_fold{fnum}'] = df_nuc['Set'].apply(lambda f: convert_fold(f,fnum))

## Scaffold-based split

Duplication of compounds is allowed in the reference split. However, the whole information of molecule is input in our model. Therefore, for the guarantee of extraporate, we built the model with Bemis-Murcko-scaffold-splitting.

In [ ]:
# !~/miniconda3/envs/mecap/bin/python _ScaffoldSplit.py \
#     --input_csv ./QMdata4ML/df_ChEMBL50K.csv.gz \
#     --smiles_col smiles \
#     --out_split_csv ./split_sim.csv \
#     --out_scaffold_map_csv ./scaf_map.csv \
#     --out_scaffold_pairs_csv ./scaf_pairs.csv \
#     --n_workers 8

In [ ]:
from tqdm import tqdm
from _rdkitAtomWiseFP import site_feature_vector, add_md_parallel_tqdm

tqdm.pandas()

spl = pd.read_csv('split.csv',index_col=0)

sf = spl['fold'].to_dict()
scaf = spl['scaffold_max_sim_to_train'].to_dict()

df_elec['Set_scaffold'] = df_elec['smiles'].map(sf)
df_nuc['Set_scaffold'] = df_nuc['smiles'].map(sf)

df_nuc['ScafMaxSim'] = df_nuc['smiles'].map(scaf)
df_elec['ScafMaxSim'] = df_elec['smiles'].map(scaf)

df_elec['rdkitAtomWiseFP'] = df_elec.progress_apply(
    lambda row: site_feature_vector(row['smiles'],row['elec_sites']), axis=1)
df_nuc['rdkitAtomWiseFP'] = df_nuc.progress_apply(
    lambda row: site_feature_vector(row['smiles'],row['nuc_sites']), axis=1)

df_elec['MDist'] = add_md_parallel_tqdm(df_elec, 'rdkitAtomWiseFP', 'Set_scaffold', n_workers=10)
df_nuc['MDist'] = add_md_parallel_tqdm(df_nuc, 'rdkitAtomWiseFP', 'Set_scaffold', n_workers=10)

100%|██████████| 534119/534119 [01:47<00:00, 4952.54it/s]
100%|██████████| 650857/650857 [02:29<00:00, 4364.72it/s]
Mahalanobis: 100%|██████████| 534119/534119 [00:02<00:00, 247790.13row/s]
Mahalanobis: 100%|██████████| 650857/650857 [00:02<00:00, 277000.93row/s]

## Save split datas

In [8]:
df_elec.to_csv('./QMdata4ML/df_elec_x_with_name_fold.csv')
df_nuc.to_csv('./QMdata4ML/df_nuc_x_with_name_fold.csv')

Now you can run the training script!

# Obtain xTB-optimized conformers (optional, but required for conformational impact analysis)

Retrieve source xTB-optimized conformers for QM-derived MCA/MAA.

In [ ]:
# Download and check included files
!wget -O calculations.tar.xz https://sid.erda.dk/share_redirect/hp3ttQcTgs; tar -tvf calculations.tar.xz | head

# Export file names
!tar -tvf calculations.tar.xz > filelist.txt

# Extract conformations (REACTANTS ONLY)
!tar --wildcards -xvf calculations.tar.xz '*/reac01/*/orca_calc.out'

In [25]:
plist = []
with open('./filelist.txt','r') as f:
    for p in f.readlines():
        if 'reac01/' in p and 'orca_calc' in p:
            plist.append(p)

In [28]:
plist[0].split()[-1].strip()

'groups/kemi/ree/PhD/applications/ESNUEL/ChEMBL50K/calculations/41203004d8954391ed1c752531b37432/reac01/conf08/gfn1/orca_calc.out'

In [ ]:
import os
from _ConvertOrcaToSDF import orca_out_to_sdf

os.makedirs('./confs_orca',exist_ok=True)
for path in plist:
    p = path.split()[-1].strip()
    orca_out_to_sdf(p,os.path.join('./confs_orca', p.split('/')[-5]+'.sdf'))

In [23]:
from rdkit import Chem

supp = Chem.SDMolSupplier('41203004d8954391ed1c752531b37432.sdf',removeHs=False)
supp[0]

# Case study: 
## A test set of 100 reaction mechanisms where the reacting function groups are similar to the functional groups in the training data of MCA* and MAA*

From [ReactivitiesDatasets in ChemDB](https://cdb.ics.uci.edu/cgibin/ReactivitiesDatasetsWeb.html)

[OBS!] Because we already provide pre-processed dataset, you DO NOT have to run below cells. Below cells are provided only for reproducibility.

In [ ]:
# # Download file
# !mkdir -p ./100_rxn_mechanisms
# !wget -O ./100_rxn_mechanisms/100_rxn_mechanisms.csv https://cdb.ics.uci.edu/cgibin/dataset-reactivities/100_rxn_mechanisms.csv

--2026-02-14 15:05:47--  https://cdb.ics.uci.edu/cgibin/dataset-reactivities/100_rxn_mechanisms.csv
Resolving cdb.ics.uci.edu (cdb.ics.uci.edu)... 128.195.8.93
Connecting to cdb.ics.uci.edu (cdb.ics.uci.edu)|128.195.8.93|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27669 (27K) [text/csv]
Saving to: ‘100_rxn_mechanisms.csv’

100_rxn_mechanisms. 100%[===================>]  27.02K  --.-KB/s    in 0.1s

2026-02-14 15:05:48 (229 KB/s) - ‘100_rxn_mechanisms.csv’ saved [27669/27669]

In [ ]:
# # Import modules for analysis
# # See: https://deeprxn.ics.uci.edu/pmechdb/howtouse

# from __future__ import annotations

# from dataclasses import dataclass
# from typing import List, Optional, Tuple
# import pandas as pd


# @dataclass(frozen=True)
# class ArrowCode:
#     src: Tuple[int, ...]  # (a,) for atom a, (a,b) for bond a-b
#     dst: Tuple[int, ...]  # (a,) for atom a, (a,b) for bond a-b

#     def __repr__(self):
#         return f'({"=".join([str(i) for i in self.src])})->({"=".join([str(i) for i in self.dst])})'


# def split_record(record: str) -> Tuple[str, Optional[str]]:
#     """
#     Split a record into (reaction_smirks, arrow_codes).
#     Assumes arrow codes, if present, appear as the last whitespace-separated token.
#     """
#     s = record.strip()
#     parts = s.rsplit(None, 1)
#     if len(parts) == 2 and ('=' in parts[1] or ';' in parts[1]):
#         return parts[0], parts[1]
#     return s, None


# def parse_arrow_codes(arrow_codes: str) -> List[ArrowCode]:
#     """
#     Parse PMechDB arrow codes.
#     Example: "10=20;20,21=21"
#     """
#     arrows: List[ArrowCode] = []
#     for chunk in arrow_codes.split(';'):
#         chunk = chunk.strip()
#         if not chunk:
#             continue
#         if '=' not in chunk:
#             raise ValueError(f'Invalid arrow code (missing "="): {chunk}')
#         left, right = chunk.split('=', 1)
#         src = tuple(int(x) for x in left.split(',') if x)
#         dst = tuple(int(x) for x in right.split(',') if x)
#         if not src or not dst:
#             raise ValueError(f'Invalid arrow code site: {chunk}')
#         arrows.append(ArrowCode(src=src, dst=dst))
#     return arrows


# def humanize_arrows(arrows: List[ArrowCode]) -> List[str]:
#     """
#     Convert arrow codes to human-readable descriptions.
#     """
#     out = {
#         'bond_form': [],
#         'pi_to_atom': [],
#         'atom_to_pi': [],
#         'unknown': [],
#         }
#     for a in arrows:
#         if len(a.src) == 1 and len(a.dst) == 1:
#             out['bond_form'] = out['bond_form'] + [a]
#         elif len(a.src) == 2 and len(a.dst) == 1:
#             out['pi_to_atom'] = out['pi_to_atom'] + [a]
#         elif len(a.src) == 1 and len(a.dst) == 2:
#             out['atom_to_pi'] = out['atom_to_pi'] + [a]
#         else:
#             out['unknown'] = out['unknown'] + [a]
#     return out


# def explain_record(record: str):
#     _, arrow_codes = split_record(record)
#     if arrow_codes is not None:
#         arrows = parse_arrow_codes(arrow_codes)
#         return humanize_arrows(arrows)
#     return


# def extract_source_and_sink(record: str) -> pd.Series:
#     bond_form = explain_record(record)['bond_form']
#     src_snk = {
#         'source': [],
#         'sink': [],
#         }
#     for bf in bond_form:
#         src_snk['source'] = src_snk['source'] + [bf.src[0]]
#         src_snk['sink'] = src_snk['sink'] + [bf.dst[0]]
#     return pd.Series({key: val[0] if len(val) == 1 else tuple(val) for key, val in src_snk.items()})

# if __name__ == '__main__':
#     rec = 'CC[Si](CC)(CC)OCC#[C-:10].CC(C)(C=C)C([CH:20]=[O:21])OCC1=CC=CC=C1>>CC[Si](CC)(CC)OCC#[C:10][CH:20](C(C(C)(C)C=C)OCC1=CC=CC=C1)[O-:21] 10=20;20,21=21'
#     print(extract_source_and_sink(rec))

source    10
sink      20
dtype: int64

In [ ]:
# from charset_normalizer import from_path
# import pandas as pd
# from rdkit import Chem

# best = from_path("100_rxn_mechanisms.csv").best()
# df = pd.read_csv("100_rxn_mechanisms.csv", encoding=best.encoding)

# df[['source','sink']] = df['SMIRKS'].apply(extract_source_and_sink)
# df_no_error = df[(df['source'].apply(lambda val: isinstance(val, int))) & (df['sink'].apply(lambda val: isinstance(val, int)))]

# uniq_reacs = {}

# for idx, smirks in df_no_error['SMIRKS'].items():
#     assert '>>' in smirks
#     for num, reac in enumerate(smirks.split('>>')[0].split('.')):
#         uniq_reacs[f'{idx}_{num}'] = reac

# uniq_reacs_df = pd.DataFrame.from_dict(uniq_reacs,orient='index',columns=['reactant_smi'])
# uniq_reacs_df['rxn_id'] = [idx.split('_')[0] for idx in uniq_reacs_df.index]
# uniq_reacs_df['mapped_atoms'] = uniq_reacs_df['reactant_smi'].apply(lambda smi: {atom.GetAtomMapNum(): atom.GetIdx() for atom in Chem.MolFromSmiles(smi).GetAtoms() if atom.GetAtomMapNum()})
# uniq_reacs_df['reactant_id_no_underbar'] = [idx.split('_')[0] for idx in uniq_reacs_df.index]

# print('Reactions with exactly one pair of electron source and sink:')
# display(df_no_error)
# print()

# print('Unique reactants:')
# display(uniq_reacs_df)

# df_no_error.to_csv('./100_rxn_mechanisms/100_rxn_mechanisms_no_error.csv')
# uniq_reacs_df.to_csv('./100_rxn_mechanisms/100_rxn_mechanisms_no_error_reactants.csv')

Reactions with exactly one pair of electron source and sink:

,SMIRKS,Source type,Sink type,Ref,source,sink
0,CC1=CC=C(C=C1)[OH:10].C1=CC=C(C=C1)[C+:20](C2=...,O phenol,C+ carbenium,Schorigin; Makarow-Semljanski[Chemische Berich...,10,20
1,C[C+:20](C)CC(C)(C)C1=C(C=CC(=C1)Br)[OH:10]>>C...,O phenol,C+ carbenium,"Vasudevan; Jayasree, Johnson; Alan T., Huang; ...",10,20
2,N#N.CC(C)=[O:10].[CH2+:20]C1=CC=CC=C1>>CC([CH3...,O=C ketone,C+ carbenium,"Fenhong Song, Ron W. Darbeau, Emil H. White J....",10,20
3,C1C[O:10]C1.C1=CC=C(C=C1)[CH+:20]C2=CC=CC=C2>>...,O ether,C+ carbenium,"Kirmse, Wolfgang; Lelgemann, Rudolf; Friedrich...",10,20
4,CC1=CCC(CC1)[C+:20](C)C.CC1(C2CC1C3(C(C2)[O:10...,O ether,C+ carbenium,"E. R. Ruckel , R. T. Wojcik & H. G. Arlt Jr. (...",10,20
...,...,...,...,...,...,...
95,COC(=O)C1(CCCCC[C:20]1=[O:21])C2=CC=CC=[C-:10]...,C- carbanion sp2,C=O ketone,"Tambar, Uttam K.; Stoltz, Brian M. J. Am. Chem...",10,20
96,COC1=CC(=[C-:10]C=C1)OC.CO[C:20](=[O:21])C1=CC...,C- carbanion sp2,C=O ester,"Louisiana State University WO2008/11508, 2008,...",10,20
97,CC(C)(C)/[N:21]=[CH:20]/C1=CC=CC=C1.[CH2-:10]C...,C- carbanion sp3,C=N imine,"Yamashita, Yasuhiro; Suzuki, Hirotsugu; Sato, ...",10,20
98,COC1=CC=C(C=C1)COCC[CH:20]=[O:21].[CH2-:10]CC=...,C- carbanion sp3,C=O aldehyde,"Masaki Ohta, Shota Kato, Tomoya Sugai, and Har...",10,20
99,CC[Si](CC)(CC)OCC#[C-:10].CC(C)(C=C)C([CH:20]=...,C- carbanion sp,C=O aldehyde,"Gregson, Thomas; Thomas, Eric J. Tetrahedron, ...",10,20

Unique reactants:

                                      reactant_smi rxn_id      mapped_atoms
0_0                          CC1=CC=C(C=C1)[OH:10]      0           {10: 7}
0_1   C1=CC=C(C=C1)[C+:20](C2=CC=CC=C2)C3=CC=CC=C3      0           {20: 6}
1_0    C[C+:20](C)CC(C)(C)C1=C(C=CC(=C1)Br)[OH:10]      1   {20: 1, 10: 14}
2_0                                            N#N      2                {}
2_1                                   CC(C)=[O:10]      2           {10: 3}
...                                            ...    ...               ...
97_1                          [CH2-:10]C1=CC=CC=C1     97           {10: 0}
98_0             COC1=CC=C(C=C1)COCC[CH:20]=[O:21]     98  {20: 12, 21: 13}
98_1                                 [CH2-:10]CC=C     98           {10: 0}
99_0                     CC[Si](CC)(CC)OCC#[C-:10]     99          {10: 10}
99_1      CC(C)(C=C)C([CH:20]=[O:21])OCC1=CC=CC=C1     99    {20: 6, 21: 7}

[190 rows x 3 columns]

In [ ]:
# df_error = df[(~df['source'].apply(lambda val: isinstance(val, int))) | (~df['sink'].apply(lambda val: isinstance(val, int)))]
# display(df_error)

,SMIRKS,Source type,Sink type,Ref,source,sink
57,COC1=CC=C(C=C1)[CH:11]=[C:10]=[N-].C1CC[C:20](...,CCN- acetonitrile anion,C=O ketone,"UNICHEM LABORATORIES LIMITEDWO2007/94008, 2007...",(),()

In [ ]:
# print(df_error.SMIRKS.iloc[0])
# print(explain_record(df_error.SMIRKS.iloc[0]))

COC1=CC=C(C=C1)[CH:11]=[C:10]=[N-].C1CC[C:20](=[O:21])CC1>>COC1=CC=C(C=C1)[CH+:11][C:10](=[N-])[C:20]2(CCCCC2)[O-:21] 10,11=10,20;20,21=21
{'bond_form': [], 'pi_to_atom': [(20=21)->(21)], 'atom_to_pi': [], 'unknown': [(10=11)->(10=20)]}

### Reference calculation

#### 1. ESNUEL (xTB -> Orca)

**Script for calculation is written in** `reference_calculation/reference_calculation.ipynb`..

Parse results after calculation

In [ ]:
# import ast
# import pandas as pd

# def literal_eval(c):
#     try:
#         return ast.literal_eval(c)
#     except:
#         return c

# smis = pd.read_csv('./100_rxn_mechanisms/100_rxn_mechanisms_no_error_reactants_calculated.txt',index_col=0).drop_duplicates(subset=['reactant_smi']).set_index('reactant_smi',drop=True).applymap(literal_eval).to_dict(orient='index')

# def concatenate_mca_maa(df: pd.DataFrame, smi_col='smiles_SMI'):
#     elec_rows = []
#     nuc_rows = []
#     for _, row in df.iterrows():
#         smi = row[smi_col]
#         di = smis[smi]
#         for t in ['mca','maa']:
#             n = 'nuc' if t=='mca' else 'elec'
#             if f'{t}_strings' not in di or not di[f'{t}_strings'] or str(di[f'{t}_strings']) == 'nan':
#                 continue
#             sites_df = pd.DataFrame.from_dict(di[f'{t}_strings'], orient='index').reset_index().rename(columns={'index': n + '_sites'})
#             sites_df[['reactant_error','product_error']] = sites_df['Error Log (Reactant, Product)'].apply(lambda l: pd.Series({'reactant_error': l.split(', ')[0], 'product_error': l.split(', ')[-1]}))
#             row_df = pd.DataFrame([row] * len(sites_df), index=range(len(sites_df)))
#             sites_df = pd.concat([row_df, sites_df.drop('Error Log (Reactant, Product)', axis=1)], axis=1)
#             if t == 'mca':
#                 nuc_rows.append(sites_df)
#             else:
#                 elec_rows.append(sites_df)

#     return pd.concat(nuc_rows).reset_index(drop=True), pd.concat(elec_rows).reset_index(drop=True)

# df = pd.read_csv('./100_rxn_mechanisms/100_rxn_mechanisms_no_error_reactants.csv',index_col=0)
# nuc_df, elec_df = concatenate_mca_maa(df, 'reactant_smi')

# nuc_df.to_csv('./100_rxn_mechanisms/100_rxn_mechanisms_no_error_reactants_calculated_nuc.csv')
# elec_df.to_csv('./100_rxn_mechanisms/100_rxn_mechanisms_no_error_reactants_calculated_elec.csv')

#### 2. ESNUEL_ML (xTB -> XGBoost)

**Script for prediction is written in** `reference_calculation/reference_calculation.ipynb`..

Parse results after prediction

In [ ]:
# import ast
# import pandas as pd

# def literal_eval(c):
#     try:
#         return ast.literal_eval(c)
#     except:
#         return c

# smis = pd.read_csv('./100_rxn_mechanisms/100_rxn_mechanisms_no_error_reactants_predicted.txt',index_col=0).drop_duplicates(subset=['reactant_smi']).set_index('reactant_smi',drop=True).applymap(literal_eval).to_dict(orient='index')

# def concatenate_mca_maa(df: pd.DataFrame, smi_col='smiles_SMI'):
#     elec_rows = []
#     nuc_rows = []
#     for _, row in df.iterrows():
#         smi = row[smi_col]
#         di = smis[smi]
#         for t in ['mca','maa']:
#             n = 'nuc' if t=='mca' else 'elec'
#             if f'{t}_strings' not in di or not di[f'{t}_strings'] or str(di[f'{t}_strings']) == 'nan':
#                 continue
#             sites_df = pd.DataFrame.from_dict(di[f'{t}_strings'], orient='index').reset_index().rename(columns={'index': n + '_sites'})
#             row_df = pd.DataFrame([row] * len(sites_df), index=range(len(sites_df)))
#             sites_df = pd.concat([row_df, sites_df.drop('Reactant', axis=1)], axis=1)
#             if t == 'mca':
#                 nuc_rows.append(sites_df)
#             else:
#                 elec_rows.append(sites_df)

#     return pd.concat(nuc_rows).reset_index(drop=True), pd.concat(elec_rows).reset_index(drop=True)

# df = pd.read_csv('./100_rxn_mechanisms/100_rxn_mechanisms_no_error_reactants.csv',index_col=0)
# nuc_df, elec_df = concatenate_mca_maa(df, 'reactant_smi')

# nuc_df.to_csv('./100_rxn_mechanisms/100_rxn_mechanisms_no_error_reactants_predicted_nuc.csv')
# elec_df.to_csv('./100_rxn_mechanisms/100_rxn_mechanisms_no_error_reactants_predicted_elec.csv')